### ISSUE TITLE
Can't register with Remember the Milk

### ISSUE THREAD

**Issue by henkjan** [Rocketeer007/TaskChecker#6]
When trying to link to my rtm account I always end up at the following message:

Uh oh... something went wrong. Don't worry though; it's not your fault. The application you're using to interact with Remember The Milk made an error. It might be worthwhile contacting the author of the application and telling them you encountered this page.

Alternatively, you might like to wait a little while and then try again.

**Comment by Rocketeer007** [comment]
In my testing, that message only appears when I try to go back to settings after successfully authenticating the app with RTM.
The first time I go to "Settings", I get the RTM login screen, and after logging in I get a success message and can see my tasks on the Pebble.

The second and subsequent time I return to the "Settings" screen, I get the error you've reported.

Can you confirm in your scenario that you have no access to tasks on the Pebble, even after re-opening the Task Checker app on the watch (and clicking the middle button, perhaps, to refresh).

**Comment by Rocketeer007** [comment]
Update - The app was already authenticated on my account; I've just de-authenticated Task Checker and retried your scenario, and I get the same result as you.

It seems something in the RTM API has changed... I will investigate further.

**Comment by Rocketeer007** [comment]
It seems that RTM made a small change... if you include a "format" parameter in the Authentication URL, the authentication fails... no idea why, since that worked fine before!

Issue has been resolved in commit 35ebb14

**Comment by henkjan** [comment]
New pebble, new phone and the same issue again.
`Uh oh... something went wrong. Don't worry though; it's not your fault. The application you're using to interact with Remember The Milk made an error. It might be worthwhile contacting the author of the application and telling them you encountered this page.

Alternatively, you might like to wait a little while and then try again.`
